Feature: Verify CB prefixed opcodes duration
  Scenario Outline: Verify CB prefixed opcodes duration
    Given the register SP set to the value BEEF
    And the register PC set to the value DEAD
    And the register HL set to the value F000
    Given the bytes CB, <Bytes>, DE, DE at the position PC
    Then the cpu has ticked <N> times for the current prefixed opcode <Name>

    Examples:
      | Name   | N | Bytes |
      | RlcB   | 2 | 00    |
      | RlcC   | 2 | 01    |
      | RlcD   | 2 | 02    |
      | RlcE   | 2 | 03    |
      | RlcH   | 2 | 04    |
      | RlcL   | 2 | 05    |
      | RlcHL  | 4 | 06    |
      | RlcA   | 2 | 07    |
      | RrcB   | 2 | 08    |
      | RrcC   | 2 | 09    |
      | RrcD   | 2 | 0A    |
      | RrcE   | 2 | 0B    |
      | RrcH   | 2 | 0C    |
      | RrcL   | 2 | 0D    |
      | RrcHL  | 4 | 0E    |
      | RrcA   | 2 | 0F    |
      | RlB    | 2 | 10    |
      | RlC    | 2 | 11    |
      | RlD    | 2 | 12    |
      | RlE    | 2 | 13    |
      | RlH    | 2 | 14    |
      | RlL    | 2 | 15    |
      | RlHL   | 4 | 16    |
      | RlA    | 2 | 17    |
      | RrB    | 2 | 18    |
      | RrC    | 2 | 19    |
      | RrD    | 2 | 1A    |
      | RrE    | 2 | 1B    |
      | RrH    | 2 | 1C    |
      | RrL    | 2 | 1D    |
      | RrHL   | 4 | 1E    |
      | RrA    | 2 | 1F    |
      | SlaB   | 2 | 20    |
      | SlaC   | 2 | 21    |
      | SlaD   | 2 | 22    |
      | SlaE   | 2 | 23    |
      | SlaH   | 2 | 24    |
      | SlaL   | 2 | 25    |
      | SlaHL  | 4 | 26    |
      | SlaA   | 2 | 27    |
      | SraB   | 2 | 28    |
      | SraC   | 2 | 29    |
      | SraD   | 2 | 2A    |
      | SraE   | 2 | 2B    |
      | SraH   | 2 | 2C    |
      | SraL   | 2 | 2D    |
      | SraHL  | 4 | 2E    |
      | SraA   | 2 | 2F    |
      | SwapB  | 2 | 30    |
      | SwapC  | 2 | 31    |
      | SwapD  | 2 | 32    |
      | SwapE  | 2 | 33    |
      | SwapH  | 2 | 34    |
      | SwapL  | 2 | 35    |
      | SwapHL | 4 | 36    |
      | SwapA  | 2 | 37    |
      | SrlB   | 2 | 38    |
      | SrlC   | 2 | 39    |
      | SrlD   | 2 | 3A    |
      | SrlE   | 2 | 3B    |
      | SrlH   | 2 | 3C    |
      | SrlL   | 2 | 3D    |
      | SrlHL  | 4 | 3E    |
      | SrlA   | 2 | 3F    |
      | Bit0B  | 2 | 40    |
      | Bit0C  | 2 | 41    |
      | Bit0D  | 2 | 42    |
      | Bit0E  | 2 | 43    |
      | Bit0H  | 2 | 44    |
      | Bit0L  | 2 | 45    |
      | Bit0HL | 3 | 46    |
      | Bit0A  | 2 | 47    |
      | Bit1B  | 2 | 48    |
      | Bit1C  | 2 | 49    |
      | Bit1D  | 2 | 4A    |
      | Bit1E  | 2 | 4B    |
      | Bit1H  | 2 | 4C    |
      | Bit1L  | 2 | 4D    |
      | Bit1HL | 3 | 4E    |
      | Bit1A  | 2 | 4F    |
      | Bit2B  | 2 | 50    |
      | Bit2C  | 2 | 51    |
      | Bit2D  | 2 | 52    |
      | Bit2E  | 2 | 53    |
      | Bit2H  | 2 | 54    |
      | Bit2L  | 2 | 55    |
      | Bit2HL | 3 | 56    |
      | Bit2A  | 2 | 57    |
      | Bit3B  | 2 | 58    |
      | Bit3C  | 2 | 59    |
      | Bit3D  | 2 | 5A    |
      | Bit3E  | 2 | 5B    |
      | Bit3H  | 2 | 5C    |
      | Bit3L  | 2 | 5D    |
      | Bit3HL | 3 | 5E    |
      | Bit3A  | 2 | 5F    |
      | Bit4B  | 2 | 60    |
      | Bit4C  | 2 | 61    |
      | Bit4D  | 2 | 62    |
      | Bit4E  | 2 | 63    |
      | Bit4H  | 2 | 64    |
      | Bit4L  | 2 | 65    |
      | Bit4HL | 3 | 66    |
      | Bit4A  | 2 | 67    |
      | Bit5B  | 2 | 68    |
      | Bit5C  | 2 | 69    |
      | Bit5D  | 2 | 6A    |
      | Bit5E  | 2 | 6B    |
      | Bit5H  | 2 | 6C    |
      | Bit5L  | 2 | 6D    |
      | Bit5HL | 3 | 6E    |
      | Bit5A  | 2 | 6F    |
      | Bit6B  | 2 | 70    |
      | Bit6C  | 2 | 71    |
      | Bit6D  | 2 | 72    |
      | Bit6E  | 2 | 73    |
      | Bit6H  | 2 | 74    |
      | Bit6L  | 2 | 75    |
      | Bit6HL | 3 | 76    |
      | Bit6A  | 2 | 77    |
      | Bit7B  | 2 | 78    |
      | Bit7C  | 2 | 79    |
      | Bit7D  | 2 | 7A    |
      | Bit7E  | 2 | 7B    |
      | Bit7H  | 2 | 7C    |
      | Bit7L  | 2 | 7D    |
      | Bit7HL | 3 | 7E    |
      | Bit7A  | 2 | 7F    |
      | Res0B  | 2 | 80    |
      | Res0C  | 2 | 81    |
      | Res0D  | 2 | 82    |
      | Res0E  | 2 | 83    |
      | Res0H  | 2 | 84    |
      | Res0L  | 2 | 85    |
      | Res0HL | 4 | 86    |
      | Res0A  | 2 | 87    |
      | Res1B  | 2 | 88    |
      | Res1C  | 2 | 89    |
      | Res1D  | 2 | 8A    |
      | Res1E  | 2 | 8B    |
      | Res1H  | 2 | 8C    |
      | Res1L  | 2 | 8D    |
      | Res1HL | 4 | 8E    |
      | Res1A  | 2 | 8F    |
      | Res2B  | 2 | 90    |
      | Res2C  | 2 | 91    |
      | Res2D  | 2 | 92    |
      | Res2E  | 2 | 93    |
      | Res2H  | 2 | 94    |
      | Res2L  | 2 | 95    |
      | Res2HL | 4 | 96    |
      | Res2A  | 2 | 97    |
      | Res3B  | 2 | 98    |
      | Res3C  | 2 | 99    |
      | Res3D  | 2 | 9A    |
      | Res3E  | 2 | 9B    |
      | Res3H  | 2 | 9C    |
      | Res3L  | 2 | 9D    |
      | Res3HL | 4 | 9E    |
      | Res3A  | 2 | 9F    |
      | Res4B  | 2 | A0    |
      | Res4C  | 2 | A1    |
      | Res4D  | 2 | A2    |
      | Res4E  | 2 | A3    |
      | Res4H  | 2 | A4    |
      | Res4L  | 2 | A5    |
      | Res4HL | 4 | A6    |
      | Res4A  | 2 | A7    |
      | Res5B  | 2 | A8    |
      | Res5C  | 2 | A9    |
      | Res5D  | 2 | AA    |
      | Res5E  | 2 | AB    |
      | Res5H  | 2 | AC    |
      | Res5L  | 2 | AD    |
      | Res5HL | 4 | AE    |
      | Res5A  | 2 | AF    |
      | Res6B  | 2 | B0    |
      | Res6C  | 2 | B1    |
      | Res6D  | 2 | B2    |
      | Res6E  | 2 | B3    |
      | Res6H  | 2 | B4    |
      | Res6L  | 2 | B5    |
      | Res6HL | 4 | B6    |
      | Res6A  | 2 | B7    |
      | Res7B  | 2 | B8    |
      | Res7C  | 2 | B9    |
      | Res7D  | 2 | BA    |
      | Res7E  | 2 | BB    |
      | Res7H  | 2 | BC    |
      | Res7L  | 2 | BD    |
      | Res7HL | 4 | BE    |
      | Res7A  | 2 | BF    |
      | Set0B  | 2 | C0    |
      | Set0C  | 2 | C1    |
      | Set0D  | 2 | C2    |
      | Set0E  | 2 | C3    |
      | Set0H  | 2 | C4    |
      | Set0L  | 2 | C5    |
      | Set0HL | 4 | C6    |
      | Set0A  | 2 | C7    |
      | Set1B  | 2 | C8    |
      | Set1C  | 2 | C9    |
      | Set1D  | 2 | CA    |
      | Set1E  | 2 | CB    |
      | Set1H  | 2 | CC    |
      | Set1L  | 2 | CD    |
      | Set1HL | 4 | CE    |
      | Set1A  | 2 | CF    |
      | Set2B  | 2 | D0    |
      | Set2C  | 2 | D1    |
      | Set2D  | 2 | D2    |
      | Set2E  | 2 | D3    |
      | Set2H  | 2 | D4    |
      | Set2L  | 2 | D5    |
      | Set2HL | 4 | D6    |
      | Set2A  | 2 | D7    |
      | Set3B  | 2 | D8    |
      | Set3C  | 2 | D9    |
      | Set3D  | 2 | DA    |
      | Set3E  | 2 | DB    |
      | Set3H  | 2 | DC    |
      | Set3L  | 2 | DD    |
      | Set3HL | 4 | DE    |
      | Set3A  | 2 | DF    |
      | Set4B  | 2 | E0    |
      | Set4C  | 2 | E1    |
      | Set4D  | 2 | E2    |
      | Set4E  | 2 | E3    |
      | Set4H  | 2 | E4    |
      | Set4L  | 2 | E5    |
      | Set4HL | 4 | E6    |
      | Set4A  | 2 | E7    |
      | Set5B  | 2 | E8    |
      | Set5C  | 2 | E9    |
      | Set5D  | 2 | EA    |
      | Set5E  | 2 | EB    |
      | Set5H  | 2 | EC    |
      | Set5L  | 2 | ED    |
      | Set5HL | 4 | EE    |
      | Set5A  | 2 | EF    |
      | Set6B  | 2 | F0    |
      | Set6C  | 2 | F1    |
      | Set6D  | 2 | F2    |
      | Set6E  | 2 | F3    |
      | Set6H  | 2 | F4    |
      | Set6L  | 2 | F5    |
      | Set6HL | 4 | F6    |
      | Set6A  | 2 | F7    |
      | Set7B  | 2 | F8    |
      | Set7C  | 2 | F9    |
      | Set7D  | 2 | FA    |
      | Set7E  | 2 | FB    |
      | Set7H  | 2 | FC    |
      | Set7L  | 2 | FD    |
      | Set7HL | 4 | FE    |
      | Set7A  | 2 | FF    |
