[package]
name = "gb-lcd"
version = "0.1.0"
authors = ["Guilhem Smith <gsmith@student.42.fr>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug_render = []

[dependencies]
sdl2 = { version = "0.35.2" }
egui = "0.16"
gl = { version = "0.14" }
egui_sdl2_gl = { git = "https://github.com/FirelightFlagboy/egui_sdl2_gl", default-features = false, rev = "14f97af830a58088c2a1e54ca2b123dbb7caf992" }
winit = "0.26.1"
winit_input_helper = "0.11.1"
pixels = "0.9.0"
