[package]
name = "gbmu"
version = "0.1.0"
authors = [
  "Guilhem Smith <gsmith@student.42.fr>",
  "Florian Bennetot <fbenneto@student.42.fr>",
  "Tiago Lernould <tlernoul@student.42.fr>",
  "Cedric M'Passi <cedricmpassi@gmail.com>"
]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug_render = ["gb-lcd/debug_render"]

[dependencies]
sdl2 = { version = "0.34", features = ["bundled", "static-link"] }
egui = { version = "0.13" }
native-dialog = { version ="0.5" }
log = "0.4"
simplelog = "0.10"
serde_yaml = { version = "0.8" }
clap = "3.0.0-beta.4"
gb-lcd = { path= "./gb-lcd" }
gb-ppu = { path = "./gb-ppu" }
gb-dbg = { path = "./gb-dbg" }
gb-joypad = { path = "./gb-joypad" }

[workspace]
members = [
  "gb-clock",
  "gb-roms",
  "gb-ppu",
  "gb-lcd",
  "gb-cpu",
  "gb-dbg",
  "gb-bus",
  "gb-rtc",
  "gb-joypad",
  "gb-timer",
  "gb-test"
]
