[package]
name = "gbmu"
version = "0.1.0"
authors = [
  "Guilhem Smith <gsmith@student.42.fr>",
  "Florian Bennetot <fbenneto@student.42.fr>",
  "Tiago Lernould <tlernoul@student.42.fr>",
  "Cedric M'Passi <cedricmpassi@gmail.com>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
debug = ["gb-lcd/debug"]

[dependencies]
sdl2 = { version = "0.34", features = ["bundled", "static-link"] }
egui = { version = "0.13" }
rfd = { version = "0.4" }
gb-lcd = { path= "./gb-lcd" }
gb-ppu = { path = "./gb-ppu" }
gb-dbg = { path = "./gb-dbg" }

[workspace]
members = [
  "gb-roms",
  "gb-ppu",
  "gb-lcd",
  "gb-dbg",
  "gb-cpu"
]
