[package]
name = "gb-dbg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_memory_editor = { git = "https://github.com/Hirtol/egui_memory_editor" }
egui = "0.13.1"
anyhow = "1.0.43"

[dev-dependencies]
eframe = "0.13.1"
