[package]
name = "gb-dbg"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_memory_editor = { git = "https://github.com/Ragarnoy/egui_memory_editor", branch = "master" }
egui = "0.14"
anyhow = "1.0.43"
log = "0.4"
gb-roms = { path = "../gb-roms" }

[dev-dependencies]
eframe = "0.14.0"

[features]
breakpoints = []
