[package]
name = "gb-dbg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui_memory_editor = "0.1.2"
egui = "0.13.1"