[package]
name = "gb-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gb-bus = { path = "../gb-bus" }
gb-cpu = { path = "../gb-cpu" }
