name: Rust

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install linux requirements
      run: sudo sh -c "apt-get update && apt-get install -y cmake libgtk-3-dev"

    - uses: actions/checkout@v2

    - name: cache cargo artifact
      uses: actions/cache@v2
      env:
        cache-name: cache-cargo-build
      with:
        path: |
          target
          ~/.cargo/registry
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Check code format
      run: cargo fmt -- --check

    - name: Lint code base
      run: cargo clippy --workspace

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
