name: Rust

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: install linux requirements
      run: sudo apt install -y cmake gtk3

    - uses: actions/checkout@v2

    - name: Check code format
      run: cargo fmt -- --check

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
